version: '3'

vars:
  PROTOBUF_VERSION: "32.1"
  # GNU grep support depending on OS
  GREP_CMD:
    sh: |
      case "$(uname)" in
        Darwin*) echo ggrep ;;
        Linux*) echo grep ;;
      esac

dotenv: ['.env']

tasks:
  ################# Development Tools ####################
  # Additional resources:
  # - https://docs.docker.com/reference/cli/docker/buildx/
  tools:
    desc: "Download tools required for development"
    deps: [install-docker-buildx]

  # Install docker-buildx
  install-docker-buildx:
    desc: "Install docker-buildx on Ubuntu"
    platforms: ["linux/amd64"]
    cmds:
      - apt install docker-buildx

  ################# Build Node.js CLI test app ####################
  build:
    desc: "Builds the js files including declarations and CLI"
    vars:
      USE_LOCAL_LIB: '{{.USE_LOCAL_CLIENT}}'
    cmds:
      - npm install
      - '{{if eq .USE_LOCAL_CLIENT "true"}}npm link @open-crypto-broker/cryptobroker-client{{end}}'
      - npm run build

  build-docker:
    desc: "Builds the Docker image for the CLI test app"
    vars:
      TAG: '{{.TAG | default "dev"}}'
    dotenv: ['.env']
    cmds:
      - |
        docker buildx build \
        --secret id=git_npm_token,env=GIT_AUTH_TOKEN \
        -f docker/Dockerfile \
        -t ghcr.io/open-crypto-broker/test_app_js:{{.TAG}} .

  delete-binaries:
    desc: "Delete binary artifacts"
    cmds:
      - npm run clean

  ################# Tests ####################
  test-hash:
    deps: [build]
    desc: "Test hashing command with Default profile"
    cmds:
      - node ./dist/cli.js --profile=Default hash "Hello"

  test-sign:
    deps: [build]
    desc: "Test certificate signing command with Default profile"
    cmds:
      - |
        rm -rf $TEST_OUTPUT_DIR
        mkdir -p $TEST_OUTPUT_DIR
        RESPONSE=$( node ./dist/cli.js --profile=Default sign \
                    --csr=$TEST_CSR_DIR/csr-nist-secp256r1.csr \
                    --caCert=$TEST_CA_DIR/cert-test-CA-nist-secp384r1.pem \
                    --caKey=$TEST_CA_DIR/test-CA-nist-secp384r1.pem)
        if echo "$RESPONSE" | {{.GREP_CMD}} -E 'Sign [Rr]esponse'; then
          SIGNED_CERTIFICATE=$(echo "$RESPONSE" | {{.GREP_CMD}} -oP '\"signedCertificate\":\s?"\K[^"]+')
          printf "$SIGNED_CERTIFICATE" > $TEST_OUTPUT_DIR/cert-response.pem
          openssl x509 -inform PEM -in $TEST_OUTPUT_DIR/cert-response.pem -text
        else
          echo -e "Certificate signing failed"
        fi

  test-health:
    deps: [build]
    desc: "Requests the server status using the CLI's health command"
    cmds:
      - node ./dist/cli.js health

  test-benchmark:
    deps: [build]
    desc: "Test benchmark command to request a server-side benchmark"
    cmds:
      - node ./dist/cli.js benchmark

  ################# Continuous Improvement Tasks ####################
  format:
    desc: "Apply formatting rules to Node.js code"
    cmds:
      - npm run format

  lint:
    desc: "Apply linting to Node.js code"
    cmds:
      - npm run lint

  vulnerability-check:
    desc: "Run vulnerability check"
    cmds:
      - npm audit

  ci:
    desc: "Runs continuous integration checks on source code"
    cmds:
    - task: format
    - task: lint
    - task: vulnerability-check
