version: '3'

dotenv: ['.env']
env:
  PATH: /usr/bin:/bin:/usr/local/bin

vars:
  # GNU grep support depending on OS
  GREP_CMD:
    sh: |
      case "$(uname)" in
        Darwin*) echo ggrep ;;
        Linux*) echo grep ;;
      esac

tasks:
  ################# Development Tools ####################
  copy-env:
    desc: "Copies example environment variables to .env file"
    cmds:
      - cp .env.example .env

  # Additional resources:
  # - https://docs.docker.com/reference/cli/docker/buildx/
  tools:
    desc: "Download tools required for development"
    deps: [install-docker-buildx, install-jq]

  # Install docker-buildx
  install-docker-buildx:
    desc: "Install docker-buildx on Ubuntu"
    platforms: ["linux/amd64"]
    cmds:
      - apt install docker-buildx

  # Install jq
  install-jq:
    desc: "Install jq on Ubuntu"
    platforms: ["linux/amd64"]
    cmds:
      - apt install jq

  ################# Build Node.js CLI test app ####################
  build:
    desc: "Builds the js files including declarations and CLI"
    vars:
      APP_NAME: '{{.APP_NAME | default "js-client-cli"}}'
      GIT_HASH:
        sh: git rev-parse HEAD
    cmds:
      - npm install
      - '{{if eq .USE_LOCAL_CLIENT "true"}}npm link @open-crypto-broker/cryptobroker-client{{end}}'
      - npm run build
      - mkdir -p bin
      - echo '{"type":"commonjs"}' > bin/package.json
      - APP_NAME={{.APP_NAME}} GIT_HASH={{.GIT_HASH}} npm run esbuild
      - chmod +x bin/{{.APP_NAME}}

  build-docker:
    desc: "Build Docker image for the CLI test app"
    vars:
      TAG: '{{.TAG | default "dev"}}'
      GIT_HASH:
        sh: git rev-parse HEAD
    cmds:
      - |
        docker buildx build \
        -f docker/Dockerfile \
        --build-arg COMMIT={{.GIT_HASH}} \
        -t ghcr.io/open-crypto-broker/test_app_js:{{.TAG}} .

  delete-binary:
    desc: "Delete binary artifact"
    vars:
      APP_NAME: '{{.APP_NAME | default "js-client-cli"}}'
    cmds:
      - npm run clean
      - rm -f bin/{{.APP_NAME}}

  ################# Tests ####################
  test-benchmark:
    deps: [build]
    desc: "Test benchmark command to request a server-side benchmark"
    vars:
      APP_NAME: '{{.APP_NAME | default "js-client-cli"}}'
    cmds:
      - ./bin/{{.APP_NAME}} benchmark | jq -r '. | select(.benchmarkResults) // empty'

  test-hash:
    deps: [build]
    desc: "Test hashing command with Default profile"
    vars:
      APP_NAME: '{{.APP_NAME | default "js-client-cli"}}'
    cmds:
      - ./bin/{{.APP_NAME}} hash --profile=Default "Hello" | jq -r '. | select(.hashValue) // empty'

  test-health:
    deps: [build]
    desc: "Requests the server status using the CLI's health command"
    vars:
      APP_NAME: '{{.APP_NAME | default "js-client-cli"}}'
    cmds:
      - ./bin/{{.APP_NAME}} health | jq '. | select(.status) // empty'

  test-sign:
    deps: [build]
    desc: "Test certificate signing command with Default profile"
    vars:
      APP_NAME: '{{.APP_NAME | default "js-client-cli"}}'
    cmds:
      - |
        rm -rf $TEST_OUTPUT_DIR
        mkdir -p $TEST_OUTPUT_DIR
        SIGNED_CERTIFICATE=$( ./bin/{{.APP_NAME}} sign --profile=Default \
          --csr=$TEST_CSR_DIR/csr-nist-secp256r1.csr \
          --caCert=$TEST_CA_DIR/cert-test-CA-nist-secp384r1.pem \
          --caKey=$TEST_CA_DIR/test-CA-nist-secp384r1.pem \
          | jq -r '.signedCertificate // empty' )

        if [ -n "$SIGNED_CERTIFICATE" ]; then
          echo "$SIGNED_CERTIFICATE" > $TEST_OUTPUT_DIR/cert-response.pem && \
          openssl x509 -inform PEM -in $TEST_OUTPUT_DIR/cert-response.pem -text
        else
          echo "Certificate signing failed!"
        fi

  ################# Continuous Improvement Tasks ####################
  npm-ci:
    desc: "Applies npm ci to install dependencies based on package-lock.json"
    env:
      HUSKY: 0
    cmds:
      - npm ci

  format:
    desc: "Apply formatting rules to Node.js code"
    cmds:
      - npm run format

  lint:
    desc: "Apply linting to Node.js code"
    cmds:
      - npm run lint

  vulnerability-check:
    desc: "Run vulnerability check"
    cmds:
      - npm audit

  ci:
    desc: "Runs continuous integration checks on source code"
    cmds:
    - task: npm-ci
    - task: format
    - task: lint
    - task: vulnerability-check
